spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/techevents
    username: techevents_user
    password: secret123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
