spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/techevents
    username: techevents_user
    password: secret123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: event-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      missing-topics-fatal: false

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  rabbitmq:
    queue: events.saved.queue
    exchange: events.saved.exchange
    routing-key: events.saved.key
    notification-exchange: notifications.exchange
    notification-routing-key: notifications.event.created
    daily-summary-routing-key: notifications.event.daily-summary


  
server:
  port: 8080
