version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: techevents-postgres
    restart: always
    environment:
      POSTGRES_DB: techevents
      POSTGRES_USER: techevents_user
      POSTGRES_PASSWORD: secret123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
